//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vertr.Moex.Generators {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vertr.Moex.Generators.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;engines&quot;: {
        ///    &quot;metadata&quot;: {
        ///      &quot;id&quot;: { &quot;type&quot;: &quot;int32&quot; },
        ///      &quot;name&quot;: {
        ///        &quot;type&quot;: &quot;string&quot;,
        ///        &quot;bytes&quot;: 45,
        ///        &quot;max_size&quot;: 0
        ///      },
        ///      &quot;title&quot;: {
        ///        &quot;type&quot;: &quot;string&quot;,
        ///        &quot;bytes&quot;: 765,
        ///        &quot;max_size&quot;: 0
        ///      }
        ///    },
        ///    &quot;columns&quot;: [ &quot;id&quot;, &quot;name&quot;, &quot;title&quot; ],
        ///    &quot;data&quot;: [
        ///      [ 1, &quot;stock&quot;, &quot;Фондовый рынок и рынок депозитов&quot; ],
        ///      [ 2, &quot;state&quot;, &quot;Рынок ГЦБ (размещение)&quot; ],
        ///      [ 3, &quot;currency&quot;, &quot;Валютный рынок&quot; ],
        ///      [ 4, &quot;futures&quot;, &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EnginesJson {
            get {
                return ResourceManager.GetString("EnginesJson", resourceCulture);
            }
        }
    }
}
