### Reference
GET https://iss.moex.com/iss/reference

### index.json
GET https://iss.moex.com/iss/index.json

### shares.columns.json
GET https://iss.moex.com/iss/engines/stock/markets/shares/securities/columns.json

### bonds.columns.json
GET https://iss.moex.com/iss/engines/stock/markets/bonds/securities/columns.json

### shares.json
GET https://iss.moex.com/iss/engines/stock/markets/shares/securities.json

### bonds.json
GET https://iss.moex.com/iss/engines/stock/markets/bonds/securities.json





