GET https://iss.moex.com/iss/reference
###

### References
GET https://iss.moex.com/iss/index.json

### Column info
GET https://iss.moex.com/iss/engines/stock/markets/shares/securities/columns.json

###
GET https://iss.moex.com/iss/engines/stock/markets/bonds/securities/columns.json

### Sec info
GET https://iss.moex.com/iss/engines/stock/markets/bonds/securities.json

###
GET https://iss.moex.com/iss/engines/stock/markets/bonds/boards/SPOB/securities.json

###
GET https://iss.moex.com/iss/engines/stock/markets/shares/securities.json

###
GET https://iss.moex.com/iss/engines/stock/markets/shares/boards/TQBR/securities.json


### Market Data



